### ISSUE TITLE
Rewriting of OpenAPI types with the same name

### ISSUE THREAD

**Issue by zhiburt** [msrd0/gotham_restful#175]
Hi

I've noticed that if we have for example 2 Resources handlers of which uses the same Request name (I guess the same applies to Response) got to be using the same schema (structure) where in reality they use different.

My guess because some type of `HashMap` is used with keys as structure names

Probably somewhere here

https://github.com/msrd0/gotham_restful/blob/fb986cf3fcdfafeb1de3da6457b474353203e2b1/src/openapi/builder.rs#L95

Example

```rust
pub mod res1 {
  #[derive(Resource)]
  #[resource(requst)]
  pub struct Resource1;
 
  #[derive(OpenapiType, Deserialize, Serialize)]
  struct Request {
      id: String,
  }

  #[create]
  async fn requst(req: Request)  -> Success<String> {
     String::new().into()
  }
}

pub mod res2 {
  #[derive(Resource)]
  #[resource(requst)]
  pub struct Resource2;
 
  #[derive(OpenapiType, Deserialize, Serialize)]
  struct Request {
      anotherId: String,
  }

  #[create]
  async fn requst(req: Request)  -> Success<String> {
     String::new().into()
  }
}
```

Once we will add them in router and check `openapi_doc` we will see that both of them have the same request, which is in reality not true.

Thank you.

**Comment by msrd0** [comment]
Yes, I'm aware of this. I believe this is documented somewhere, but I can't find it right now, so maybe I should make this behaviour more clear in the documentation.

The issue is actually much more involved than just not using a hashmap in this crate - the `openapi_type` crate will already produce an invalid schema if you have code like this:

```rust
mod foo1 {
    struct Foo { id: u64 }
}
mod foo2 {
    struct Foo { another_id: u64 }
}

struct Bar {
    foo1: foo1::Foo,
    foo2: foo2::Foo
}
```

The schema will not make any difference between these two types. For now, you will have to ensure manually that all types have unique names.

**Comment by zhiburt** [comment]
Thank you for clarification.
And sorry that I did not tried to make sure that it did documented somewhere :sweat_smile:  

Then I'm closing it.

Take care.
